### PR TITLE
Update for Maven users

### PR DESCRIPTION
**Pull request by sytolk**

### CODE REVIEW

**Comment by commonsguy** [comment]
I do not use Maven as a build system and am in no position to support Maven users. Thanks, though!

**Comment by sytolk** [comment]
"I do not use Maven" really ? look in you build.gradle
```
repositories {
    maven {
        url "https://s3.amazonaws.com/repo.commonsware.com"
    }
}
```
you have use Maven repository ;)
Its not need to support Maven users you can continue to use your gradle build. This info in readme is to save time for the users that use Maven as build system. I have successful use your AAR gradle build from my Maven project and wants to share HOW TO with other Maven users.

**Comment by commonsguy** [comment]
>you have use Maven repository ;)

A Maven repository is not the Maven build system.

**Comment by sytolk** [comment]
Yes I know :)

**Pull request closed without merging**
